spring:
  application:
    name: zuul

server:
  port: 6001

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:2002/eureka

zuul:
  routes:
    user-service: /user-service/**
#    ticket-service: /ticket-service/**


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
    