test:
  user-service:
    users: "[{\"id\":7, \"username\":\"abc\",\"password\":\"123\"},{\"id\":8, \"username\":\"def\",\"password\":\"456\"},{\"id\":9, \"username\":\"ghi\",\"password\":\"789\"}]"

spring:
  application:
    name: user-service

  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ysstech?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root

#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.yss.commons.demo.entity
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 3002
  
eureka:
  client:
    service-url: 
      defaultZone: http://127.0.0.1:2002/eureka
#负载均衡全局配置 
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  
#对特定服务负载均衡的配置  
user-service:
  ribbon:
    ConnectTimeout: 500
    ReadTimeout: 1000
    MaxAutoRetriesNextServer: 2
    MaxAutoRetries: 1
  
  
feign:
  hystrix:
    enabled: true

#降级，超过500毫秒调用降级方法
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500  
            
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream 